import type { CSSProperties } from "react";

export const overlayStyles: Record<string, CSSProperties> = {
  // ─── Layout ───
  backdrop: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0, 0, 0, 0.6)",
    zIndex: 99999,
    display: "flex",
    alignItems: "center",
    justifyContent: "center",
    animation: "unravel-fade-in 0.2s ease-out",
  },
  container: {
    width: "90vw",
    maxWidth: "1100px",
    height: "80vh",
    maxHeight: "700px",
    backgroundColor: "#1a1a2e",
    color: "#e0e0e0",
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    fontSize: "14px",
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
    borderRadius: "12px",
    boxShadow: "0 25px 60px rgba(0, 0, 0, 0.5), 0 0 0 1px rgba(255, 255, 255, 0.08)",
    animation: "unravel-slide-up 0.25s ease-out",
  },
  header: {
    display: "flex",
    alignItems: "center",
    padding: "12px 20px",
    borderBottom: "1px solid #333",
    backgroundColor: "#1a1a2e",
    gap: "12px",
    flexShrink: 0,
  },
  logo: {
    fontWeight: 700,
    fontSize: "16px",
    color: "#7c3aed",
    flexShrink: 0,
  },
  errorType: {
    color: "#ef4444",
    fontFamily: 'ui-monospace, "Cascadia Code", Menlo, monospace',
    fontSize: "13px",
    flex: 1,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  closeBtn: {
    background: "none",
    border: "1px solid #555",
    color: "#999",
    cursor: "pointer",
    padding: "4px 8px",
    borderRadius: "4px",
    fontSize: "14px",
    flexShrink: 0,
  },
  body: {
    display: "flex",
    flex: 1,
    overflow: "hidden",
  },
  leftPanel: {
    flex: 1,
    padding: "20px",
    overflowY: "auto",
    borderRight: "1px solid #333",
    minWidth: 0,
  },
  rightPanel: {
    flex: 1,
    padding: "20px",
    overflowY: "auto",
    minWidth: 0,
  },

  // ─── Typography ───
  pre: {
    fontFamily: 'ui-monospace, "Cascadia Code", Menlo, monospace',
    fontSize: "12px",
    lineHeight: 1.6,
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
    margin: 0,
    color: "#ccc",
  },
  heading: {
    fontSize: "13px",
    fontWeight: 600,
    textTransform: "uppercase" as const,
    letterSpacing: "0.05em",
    color: "#888",
    marginBottom: "8px",
    marginTop: "16px",
  },

  // ─── Confidence Badge ───
  badge: {
    display: "inline-block",
    padding: "2px 8px",
    borderRadius: "4px",
    fontSize: "11px",
    fontWeight: 600,
    textTransform: "uppercase" as const,
  },
  badgeHigh: { backgroundColor: "#166534", color: "#4ade80" },
  badgeMedium: { backgroundColor: "#854d0e", color: "#facc15" },
  badgeLow: { backgroundColor: "#991b1b", color: "#fca5a5" },

  // ─── Root Cause ───
  rootCause: {
    fontSize: "15px",
    fontWeight: 500,
    color: "#f0f0f0",
    marginTop: "8px",
    marginBottom: "16px",
    lineHeight: 1.5,
  },

  // ─── Tabs ───
  tabBar: {
    display: "flex",
    borderBottom: "1px solid #333",
    marginBottom: "16px",
    gap: "4px",
  },
  tab: {
    padding: "8px 16px",
    cursor: "pointer",
    border: "none",
    background: "none",
    color: "#888",
    fontSize: "13px",
    fontWeight: 500,
    borderBottom: "2px solid transparent",
    display: "flex",
    alignItems: "center",
    gap: "6px",
  },
  tabActive: {
    color: "#e0e0e0",
    borderBottom: "2px solid #7c3aed",
  },
  tabCount: {
    backgroundColor: "#333",
    color: "#aaa",
    fontSize: "10px",
    fontWeight: 600,
    padding: "1px 5px",
    borderRadius: "8px",
    minWidth: "16px",
    textAlign: "center",
  },

  // ─── File Cards ───
  fileCard: {
    backgroundColor: "#1e1e2e",
    borderRadius: "6px",
    padding: "12px",
    marginBottom: "8px",
    border: "1px solid #333",
  },
  filePath: {
    fontFamily: 'ui-monospace, "Cascadia Code", Menlo, monospace',
    fontSize: "12px",
    color: "#7c3aed",
    marginBottom: "6px",
    fontWeight: 500,
  },
  fileIssue: {
    color: "#ef4444",
    fontSize: "13px",
    marginBottom: "4px",
    lineHeight: 1.4,
  },
  fileFix: {
    color: "#4ade80",
    fontSize: "13px",
    lineHeight: 1.4,
  },

  // ─── Fix Guide Steps ───
  step: {
    padding: "10px 0",
    borderBottom: "1px solid #2a2a2a",
    lineHeight: 1.5,
    display: "flex",
    gap: "10px",
    alignItems: "flex-start",
  },
  stepNumber: {
    color: "#7c3aed",
    fontWeight: 700,
    fontSize: "13px",
    flexShrink: 0,
    minWidth: "18px",
  },

  // ─── AI Prompt ───
  promptBox: {
    fontFamily: 'ui-monospace, "Cascadia Code", Menlo, monospace',
    fontSize: "12px",
    lineHeight: 1.6,
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
    margin: 0,
    color: "#ccc",
    backgroundColor: "#1e1e2e",
    padding: "16px",
    borderRadius: "6px",
    border: "1px solid #333",
  },
  copyBtn: {
    padding: "8px 16px",
    backgroundColor: "#7c3aed",
    color: "#fff",
    border: "none",
    borderRadius: "4px",
    cursor: "pointer",
    fontSize: "12px",
    fontWeight: 500,
    marginTop: "12px",
    transition: "background-color 0.2s",
  },
  copyBtnSuccess: {
    backgroundColor: "#166534",
  },

  // ─── Prevention Tip ───
  preventionBox: {
    marginTop: "20px",
    padding: "12px",
    backgroundColor: "#1a1a2e",
    borderRadius: "6px",
    borderLeft: "3px solid #7c3aed",
  },
  preventionLabel: {
    fontSize: "11px",
    fontWeight: 600,
    textTransform: "uppercase" as const,
    letterSpacing: "0.05em",
    color: "#7c3aed",
    marginBottom: "4px",
  },
  preventionText: {
    color: "#ccc",
    lineHeight: 1.5,
    fontSize: "13px",
  },

  // ─── Loading ───
  loadingContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    height: "100%",
    gap: "16px",
  },
  loadingText: {
    color: "#888",
    fontSize: "14px",
  },
  spinner: {
    width: "24px",
    height: "24px",
    border: "3px solid #333",
    borderTopColor: "#7c3aed",
    borderRadius: "50%",
    animation: "unravel-spin 0.8s linear infinite",
  },
};
