import type { CSSProperties } from "react";

export const overlayStyles: Record<string, CSSProperties> = {
  container: {
    position: "fixed",
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: "rgba(0, 0, 0, 0.95)",
    color: "#e0e0e0",
    fontFamily: '-apple-system, BlinkMacSystemFont, "Segoe UI", Roboto, sans-serif',
    fontSize: "14px",
    zIndex: 99999,
    display: "flex",
    flexDirection: "column",
    overflow: "hidden",
  },
  header: {
    display: "flex",
    alignItems: "center",
    padding: "12px 20px",
    borderBottom: "1px solid #333",
    backgroundColor: "#1a1a2e",
    gap: "12px",
  },
  logo: {
    fontWeight: 700,
    fontSize: "16px",
    color: "#7c3aed",
    flexShrink: 0,
  },
  errorType: {
    color: "#ef4444",
    fontFamily: 'ui-monospace, "Cascadia Code", Menlo, monospace',
    fontSize: "13px",
    flex: 1,
    overflow: "hidden",
    textOverflow: "ellipsis",
    whiteSpace: "nowrap",
  },
  closeBtn: {
    background: "none",
    border: "1px solid #555",
    color: "#999",
    cursor: "pointer",
    padding: "4px 8px",
    borderRadius: "4px",
    fontSize: "14px",
    flexShrink: 0,
  },
  body: {
    display: "flex",
    flex: 1,
    overflow: "hidden",
  },
  leftPanel: {
    flex: 1,
    padding: "20px",
    overflowY: "auto",
    borderRight: "1px solid #333",
  },
  rightPanel: {
    flex: 1,
    padding: "20px",
    overflowY: "auto",
  },
  pre: {
    fontFamily: 'ui-monospace, "Cascadia Code", Menlo, monospace',
    fontSize: "12px",
    lineHeight: 1.6,
    whiteSpace: "pre-wrap",
    wordBreak: "break-word",
    margin: 0,
    color: "#ccc",
  },
  heading: {
    fontSize: "13px",
    fontWeight: 600,
    textTransform: "uppercase" as const,
    letterSpacing: "0.05em",
    color: "#888",
    marginBottom: "8px",
    marginTop: "16px",
  },
  badge: {
    display: "inline-block",
    padding: "2px 8px",
    borderRadius: "4px",
    fontSize: "11px",
    fontWeight: 600,
    textTransform: "uppercase" as const,
  },
  badgeHigh: { backgroundColor: "#166534", color: "#4ade80" },
  badgeMedium: { backgroundColor: "#854d0e", color: "#facc15" },
  badgeLow: { backgroundColor: "#991b1b", color: "#fca5a5" },
  rootCause: {
    fontSize: "15px",
    fontWeight: 500,
    color: "#f0f0f0",
    marginTop: "8px",
    marginBottom: "16px",
    lineHeight: 1.5,
  },
  tab: {
    padding: "8px 16px",
    cursor: "pointer",
    border: "none",
    background: "none",
    color: "#888",
    fontSize: "13px",
    fontWeight: 500,
    borderBottom: "2px solid transparent",
  },
  tabActive: {
    color: "#e0e0e0",
    borderBottom: "2px solid #7c3aed",
  },
  tabBar: {
    display: "flex",
    borderBottom: "1px solid #333",
    marginBottom: "16px",
  },
  copyBtn: {
    padding: "6px 12px",
    backgroundColor: "#7c3aed",
    color: "#fff",
    border: "none",
    borderRadius: "4px",
    cursor: "pointer",
    fontSize: "12px",
    fontWeight: 500,
    marginTop: "8px",
  },
  step: {
    padding: "8px 0",
    borderBottom: "1px solid #2a2a2a",
    lineHeight: 1.5,
  },
  fileCard: {
    backgroundColor: "#1e1e2e",
    borderRadius: "6px",
    padding: "12px",
    marginBottom: "8px",
    border: "1px solid #333",
  },
  filePath: {
    fontFamily: 'ui-monospace, "Cascadia Code", Menlo, monospace',
    fontSize: "12px",
    color: "#7c3aed",
    marginBottom: "4px",
  },
  fileIssue: {
    color: "#ef4444",
    fontSize: "13px",
    marginBottom: "4px",
  },
  fileFix: {
    color: "#4ade80",
    fontSize: "13px",
  },
  loadingContainer: {
    display: "flex",
    flexDirection: "column",
    alignItems: "center",
    justifyContent: "center",
    height: "100%",
    gap: "16px",
  },
  loadingText: {
    color: "#888",
    fontSize: "14px",
  },
  spinner: {
    width: "24px",
    height: "24px",
    border: "3px solid #333",
    borderTopColor: "#7c3aed",
    borderRadius: "50%",
    animation: "unravel-spin 0.8s linear infinite",
  },
};
